name: run-coverage

on:
  pull_request:
    types: [assigned,  opened,  synchronize,  reopened]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23'

    - run: npm install
    - run: npm run package

    - uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: test/_stubs/coverage-summary-99-pct.json
        title: End to End Test Coverage
